account/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from account.views import LoginView, LogoutView, SignUpView, PostListView,PostDetailView, PostCreateView,ProfileView, \
     ProfileListView, RegisterView, PostUpdateView,PostDeleteView, CommentAdd, ProfileUpdateView, AccountUpdateView, \
     TagIndexView
from . import views

urlpatterns = [

    url(r'^login/$', LoginView.as_view(),  name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='my_logout'),
    url(r'^signup/$', RegisterView.as_view(), name='sign_up'),
    #url(r'^post_list/$', PostListView.as_view(), name='post_list'),
    url(r'^post_create/$', PostCreateView.as_view(), name='post_create'),
    url(r'^post/(?P<pk>\d+)/update/$', PostUpdateView.as_view(), name='post_update'),
    url(r'^post/(?P<pk>\d+)/delete/$', PostDeleteView.as_view(), name='post_delete'),
    url(r'^tag/(?P<slug>[-\w]+)/$', TagIndexView.as_view(), name='tagged'),
    url(r'^blog/(?P<pk>\d+)/$', PostDetailView.as_view(), name='post_detail'),
    url(r'^profile/(?P<pk>\d+)/details/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/$', ProfileListView.as_view(), name='profile_list'),
    url(r'^profile/(?P<pk>\d+)/settings/$', ProfileUpdateView.as_view(), name='profile_update'),
    url(r'^account_update/(?P<pk>\d+)/$', AccountUpdateView.as_view(), name='account_update'),
    url(r'^comment/add/$', CommentAdd.as_view(), name='comment_add'),
    url(r'^like/$', views.post_like, name='like'),
    url(r'^select2/', include('django_select2.urls')),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from account.views import PostListView

urlpatterns = [
    #url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^$', PostListView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings. MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, AuthenticationForm
from .models import User, Post, Profile, Comment
from account.utils import BootstrapMixin
from django.contrib.auth import authenticate, get_user_model
from django.http import HttpResponseRedirect
from django.utils import timezone
from taggit.models import Tag
from django_select2.forms import Select2MultipleWidget

class UserAdminCreationForm(BootstrapMixin, forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=False):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserCreationForm(BootstrapMixin, forms.Form):
    email = forms.EmailField(label='email address',
                              max_length=255)

    nickname = forms.CharField(label='nickname', max_length=20)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Profile "%s" is already in use.' % email)
        else:
            return email
    def clean_nickname(self):
        nickname = self.cleaned_data['nickname']
        filtered = Profile.objects.filter(nickname=nickname).exists()
        if filtered:
            raise forms.ValidationError('Profile "%s" is already in use.' % nickname)
        return nickname



class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class AuthForm(BootstrapMixin, AuthenticationForm):

    pass

def past_years(ago):
    this_year = timezone.now().year
    return list(range(this_year-ago-1, this_year))

class ProfileForm(BootstrapMixin, forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)
        widgets = {
            'nickname': forms.TextInput(attrs={'size': 50, 'title': 'Enter your nickname'}),
            'date_of_birth': forms.SelectDateWidget(years=past_years(100))
        }

class CommentForm(BootstrapMixin, forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('nickname', 'body', 'post')
        widgets = {'nickname': forms.HiddenInput(), 'post': forms.HiddenInput(),
                   'body': forms.Textarea(attrs={'size': 100, 'placeholder': 'Enter your comment', 'rows': 2, 'cols':  100 })}

class PostForm(BootstrapMixin, forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'tags', 'body', 'status']
        widgets = {
            'tags' : Select2MultipleWidget()
        }


class AccountUpdateForm(BootstrapMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

account/views.py
from django.utils.http import is_safe_url
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout, authenticate
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView, ListView, DetailView, UpdateView,DeleteView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from account.forms import UserAdminCreationForm, AuthForm, UserCreationForm, CommentForm, ProfileForm, \
     AccountUpdateForm, PostForm
from django.contrib.messages.views import SuccessMessageMixin
from account.models import Post, Profile, User, Comment
from django.db.models import Q
from django.core.urlresolvers import reverse_lazy
from django.utils.text import slugify

from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from django.contrib.auth.decorators import login_required
from hitcount.views import HitCountDetailView
from taggit.models import Tag
from django.db.models import Count
# Create your views here.


####################################
    ##  Authentication ##
####################################

class LoginView(FormView):
    """
       Provides the ability to login as a user with a username and password
    """
    template_name = 'account/login.html'
    success_url = '/'
    form_class = AuthForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)

    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to

class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    url = '/account/login/'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

class SignUpView(SuccessMessageMixin, FormView):
    template_name = 'account/signup.html'
    success_url = '/'
    form_class = UserAdminCreationForm
    success_message = "Account was created successfully"

    def form_valid(self, form):
        form.save()
        profile = Profile.objects.create(nickname=self.request.user.nickname, user=self.request.user)
        # get the username and password
        email = self.request.POST['email']
        password = self.request.POST['password1']
        # authenticate user then login
        new_user = authenticate(email=email, password=password)
        auth_login(self.request, new_user)
        return super(SignUpView, self).form_valid(form)

class RegisterView(SuccessMessageMixin, FormView):
    template_name = 'account/signup.html'
    success_url = '/'
    form_class = UserCreationForm
    success_message = "Account was created successfully"

    def form_valid(self, form):
        user = User.objects.create_user(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password1'],
        )
        profile = Profile.objects.create(nickname=form.cleaned_data['nickname'], user=user)

        auth_login(self.request, user)
        return super(RegisterView, self).form_valid(form)


####################################
    ##  POST VIEWS ##
####################################

class PostListView(ListView):
    model = Post
    template_name = 'account/post_list.html'
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['ordering_posts']= Post.objects.order_by("-hit_count_generic__hits")[:6]

        return context

    def get_queryset(self):
        queryset = Post.objects.all()
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(Q(title__icontains=query) |
                                       Q(body__icontains=query)|
                                       Q(tags__name__icontains=query)
                                       ).distinct()
            return queryset
        else:
            return Post.published.all()



class TagIndexView(ListView):
    model = Post
    template_name = 'account/post_list.html'
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super(TagIndexView, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs.get('slug'))

class PostDetailView(HitCountDetailView):
    model = Post
    template_name = 'account/post_detail.html'
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['ordering_posts'] = Post.objects.order_by("-hit_count_generic__hits")[:6]
        #list of similar posts
        post = self.object
        post_tags_ids = post.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
        context['similar_posts'] = similar_posts.annotate(same_tags=Count('tags')) \
                            .order_by('-same_tags', '-publish')[:4]
        #commentform
        if self.request.user.is_authenticated():
            context['comment_form'] = CommentForm(initial={'post': self.object, 'nickname': self.request.user.profile.pk})
        return context

class PostCreateView(SuccessMessageMixin,LoginRequiredMixin, CreateView):
    login_url = '/account/login/'

    template_name = 'account/post_create.html'
    success_url = '/'
    form_class = PostForm

    success_message = "Post was created successfully"


    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title, allow_unicode=True)
        form.save()
        return super(PostCreateView, self).form_valid(form)

class PostUpdateView(SuccessMessageMixin,LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'account/post_update.html'
    login_url = '/login/'
    success_message = "Post was updated successfully"
    success_url = reverse_lazy('account:profile')
    fields = ('title', 'body', 'status',)

    def get_success_url(self):
        return reverse_lazy('account:profile', kwargs={'pk': self.request.user.id})

class PostDeleteView(SuccessMessageMixin,LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'account/post_delete.html'
    login_url = '/login/'
    success_message = "Post was deleted successfully"

    def get_success_url(self):
        return reverse_lazy('account:profile', kwargs={'pk': self.request.user.id})

class CommentAdd(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'account/comment_add.html'


####################################
    ##  PROFILE VIEWS##
####################################

class ProfileView(DetailView):
    model = Profile
    template_name = 'account/profile_page.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(author=self.kwargs['pk'])
        return context

class ProfileListView(ListView):
    model = Profile
    template_name = 'account/profile_list.html'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super(ProfileListView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        queryset = Profile.objects.all()
        query = self.request.GET.get('q')

        if query:
            queryset = queryset.filter(Q(user__first_name__icontains=query) |
                                       Q(user__last_name__icontains=query) |
                                       Q(nickname__icontains=query) |
                                       Q(user__email__icontains=query)
                                          ).distinct()
            return queryset
        else:
            return Profile.objects.all()

class ProfileUpdateView(SuccessMessageMixin,LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'account/Profile_settings/profile_settings.html'
    login_url = '/login/'
    success_message = "Profile was updated successfully"

    def get_success_url(self):
        return reverse_lazy('account:profile', kwargs={'pk': self.request.user.profile.id})

class AccountUpdateView(SuccessMessageMixin,LoginRequiredMixin, UpdateView):
    model = User
    form_class = AccountUpdateForm
    login_url = '/login/'
    success_message = "Account was updated successfully"
    template_name = 'account/Profile_settings/account_settings.html'

    def get_success_url(self):
        return reverse_lazy('account:profile', kwargs={'pk': self.request.user.profile.id})

@ajax_required
@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:

account/templates/base.html
{% load staticfiles %}
{% load thumbnail %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>

    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "font-awesome-4.7.0/css/font-awesome.min.css" %}">
    {% block head %}
    {% endblock %}
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url "home" %}">Habrabobr</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <li class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url "home" %}">Posts <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:profile_list' %}">Users</a>
              </li>
            </ul>

              <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                      <form class="form-inline" method="get">
                      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}"/>
                      <button class="btn btn-outline-secondary mr-5 my-sm-0" type="submit">Search</button>
                      </form>
                  </li>

                  {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="btn btn-outline-info" href="{% url "account:post_create" %}">Create <span class="sr-only">(current)</span></a>
                        </li>
                      <li class="nav-item dropdown profile-menu">
                            {% if user.profile.photo %}
                                {% thumbnail user.profile.photo "40x40" crop="100% center" as im %}
                                    <img src="{{ im.url}}" class="rounded-circle dropdown-toggle " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                                {% endthumbnail %}
                            {% else %}
                                <img src="{% static 'img/base_auth/user_without_icon.jpg' %}" class="rounded-circle dropdown-toggle " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 40px; height: 40px">

                            {% endif %}

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">

                              <a class="dropdown-item" href="#"><i class="fa fa-clipboard fa-sm " > Posts</i></a>
                              <a class="dropdown-item" href="{% url 'account:profile' user.profile.pk %}"><i class="fa fa-user-circle fa-sm " > Profile</i></a></a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{% url 'account:profile_update' user.profile.pk %}"><i class="fa fa-cog fa-sm " > Profile settings</i></a>
                              <a class="dropdown-item" href="{% url "account:my_logout" %}"><i class="fa fa-sign-out fa-sm " > Log-out</i></a>

                            </div>

                      </li>
                  {% else %}
                      <li class="nav-item">
                        <a class="btn btn-outline-primary" href="{% url "account:login" %}">Log-In</a>
                        <a class="btn btn-outline-success" href="{% url "account:sign_up" %}">Sign-Up</a>
                      </li>
                  {% endif %}

              </ul>
          </li>
        </nav>
    </header>


    <main role="main" id="content-main" class="container">
        <div class="row">
                <div class="col-lg-9">
                    {% block content %}
                    {% endblock %}
                </div>

                <div class="col-lg-3">
                    {% block sidebar %}
                    {% endblock %}
                </div>
            </div>
    </main>

    <footer class="footer ">
        <div class="container">
             <div class="row">
                <div class="col-lg-2">
                </div>
            <div class="col-lg-7">
                <ul class="list-inline list-unstyled">
                <li class="list-inline-item"><a href="#">Habrabobr</a></li>
                <li class="list-inline-item"><a href="#">Twitter</a></li>
                <li class="list-inline-item"><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-lg-3">
                <address>
                    <strong>Name, Inc.</strong>
                </address>
            </div>
            </div>
        </div>
    </footer>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>

    <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $(document).ready(function(){

            $('.profile-menu')
                .mouseenter(function() {
                  $('.dropdown-menu ').show('100');

                });


            $('.dropdown-menu').mouseleave(function() {
                  $('.dropdown-menu ').hide();
                });
            {% block domready %}
            {% endblock %}
        });


    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>


    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

    {{ form.media.js }}
</body>

account/templates/base_auth.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>

    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url "home" %}">Habrabobr</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url "home" %}">Home <span class="sr-only">(current)</span></a>
              </li>
            </ul>

              <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="btn btn-outline-primary" href="{% url "account:login" %}">Log-In</a>
                    <a class="btn btn-outline-success" href="{% url "account:sign_up" %}">Sign-Up</a>
                  </li>
              </ul>
          </div>
        </nav>
    </header>


    <main role="main" id="main-auth" class="container">
        <div class="row">
                <div class="col-3">
                   <h2 class="text-center">Habrabobr</h2>
                     <hr>
                     <p class="text-center">Community of IT specialists </p>
                </div>
                <div class="col-3">
                    <br>
                    <div>
                          <img class="rounded" src="{% static 'img/base_auth/information2.jpg' %}" alt="" height="200" width="270">
                          <p class="text-center">Tons of interesting information</p>
                    </div>
                    <br>
                    <div>
                          <img class="rounded" src="{% static 'img/base_auth/people.png' %}" alt="" height="140" width="270">
                          <p class="text-center">Constructive dialogues</p>
                    </div>
                    <div>
                          <img class="rounded" src="{% static 'img/base_auth/star2.png' %}" alt="" height="250" width="200">
                          <p class="text-center">Blogs of leading IT specialists</p>
                    </div>
                </div>
                <div class="col-6">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
    </main>

    <footer class="footer">
            <div class="row">
                <div class="col-lg-2">
                </div>
            <div class="col-lg-7">
                <ul class="list-inline list-unstyled">
                <li class="list-inline-item"><a href="#">Habrabobr</a></li>
                <li class="list-inline-item"><a href="#">Twitter</a></li>
                <li class="list-inline-item"><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-lg-3">
                <address>
                    <strong>Name, Inc.</strong>
                </address>
            </div>
            </div>

    </footer>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>